name: Backend CI & Security Pipeline
on:
  push:
    branches: ['**'] 
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'backend/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and run unit tests with Maven
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn -B verify --file backend/pom.xml
      
      - name: Upload Maven target directory
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: backend/target

  security_scans:
    name: Security Scans
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          report_format: sarif 
          report_path: gitleaks-report.sarif
          no_fail: true 

      - name: Upload GitLeaks Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif

      - name: OWASP Dependency-Check Scan
        uses: owasp/dependency-check-action@v5
        with:
          project: 'plateforme-rh'
          path: '.'
          format: 'SARIF'
          args: '--scan backend' 

      - name: Upload Dependency-Check Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'reports/dependency-check-report.sarif'
  
  sonarcloud_analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build 
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarCloud & Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.sonar/cache
            ~/.m2
          key: ${{ runner.os }}-sonar-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-m2
      
      - name: Download Maven target directory
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: backend/target

      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=firass-gh_Plateforme-RH \
            --file backend/pom.xml # Specify the pom.xml location within the monorepo
